apiVersion: v1
kind: ConfigMap
# This is for the email notification
metadata:
  name: email-config
data:
  service.email.gmail: |
    username: fmsreadonly@gmail.com
    password: usfhxqhpiccbwgbl
    host: smtp.gmail.com
    port: 464
    from: readonly@fms.com

